// Phosphor icons used by the screen mock-ups, mapped from the design's `ph ph-<name>` classes.
// Imported one by one so the bundle only contains these icons.
import {
  AirplaneTilt,
  Armchair,
  ArrowCounterClockwise,
  ArrowRight,
  BatteryFull,
  CalendarCheck,
  CalendarDots,
  CalendarPlus,
  CaretLeft,
  CaretRight,
  CellSignalFull,
  ChartBar,
  ChatCircle,
  Clock,
  CoffeeBean,
  Copy,
  DownloadSimple,
  Fire,
  Funnel,
  GearSix,
  List,
  MagnifyingGlass,
  MapPin,
  MoonStars,
  Package,
  PaperPlaneTilt,
  Phone,
  Plus,
  Receipt,
  SquaresFour,
  Truck,
  UserCircle,
  UserPlus,
  Users,
  UsersThree,
  WhatsappLogo,
  WifiHigh,
} from '@phosphor-icons/react'

const ICONS = {
  'airplane-tilt': AirplaneTilt,
  'armchair': Armchair,
  'arrow-counter-clockwise': ArrowCounterClockwise,
  'arrow-right': ArrowRight,
  'battery-full': BatteryFull,
  'calendar-check': CalendarCheck,
  'calendar-dots': CalendarDots,
  'calendar-plus': CalendarPlus,
  'caret-left': CaretLeft,
  'caret-right': CaretRight,
  'cell-signal-full': CellSignalFull,
  'chart-bar': ChartBar,
  'chat-circle': ChatCircle,
  'clock': Clock,
  'coffee-bean': CoffeeBean,
  'copy': Copy,
  'download-simple': DownloadSimple,
  'fire': Fire,
  'funnel': Funnel,
  'gear-six': GearSix,
  'list': List,
  'magnifying-glass': MagnifyingGlass,
  'map-pin': MapPin,
  'moon-stars': MoonStars,
  'package': Package,
  'paper-plane-tilt': PaperPlaneTilt,
  'phone': Phone,
  'plus': Plus,
  'receipt': Receipt,
  'squares-four': SquaresFour,
  'truck': Truck,
  'user-circle': UserCircle,
  'user-plus': UserPlus,
  'users': Users,
  'users-three': UsersThree,
  'whatsapp-logo': WhatsappLogo,
  'wifi-high': WifiHigh,
}

// The design's icon font sizes icons with font-size; Phosphor's React icons default to 1em, so the same
// styles work unchanged.
export function Ph({ name, style, className }) {
  const Icon = ICONS[name]
  return Icon ? <Icon style={style} className={className} /> : null
}
